apiVersion: apps/v1
kind: Deployment
metadata:
  name: banquito-ws-productos-pasivos
  labels:
    app: banquito-ws-productos-pasivos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banquito-ws-productos-pasivos
  template:
    metadata:
      name: banquito-ws-productos-pasivos
      labels:
        app: banquito-ws-productos-pasivos
    spec:
      containers:
        - name: banquito-ws-productos-pasivos
          image: g2acrrepo.azurecr.io/sochoa1705/banquito-ws-productos-pasivos:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080



      